# Generated by Django 5.1.7 on 2025-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "domaine",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("art", "Art"),
                            ("finance", "Finance"),
                            ("business", "Business"),
                            ("cinema", "Cinéma"),
                            ("maths", "Maths"),
                            ("informatique", "Informatique"),
                            ("ia", "Intelligence Artificielle"),
                        ],
                        max_length=30,
                    ),
                ),
                ("lieu", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
