# Generated by Django 5.1.7 on 2025-04-02 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        default="debutant",
                        max_length=20,
                    ),
                ),
                ("points", models.FloatField(default=0.0)),
                ("prenom", models.CharField(blank=True, max_length=100)),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("H", "Homme"), ("F", "Femme"), ("A", "Autre")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("type_de_membre", models.CharField(blank=True, max_length=100)),
                ("societe", models.CharField(blank=True, max_length=100)),
                ("show_prenom", models.BooleanField(default=True)),
                ("show_nom", models.BooleanField(default=False)),
                ("show_date_naissance", models.BooleanField(default=True)),
                ("show_sexe", models.BooleanField(default=True)),
                ("show_photo", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
