# Generated by Django 5.2 on 2025-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0002_profilutilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilutilisateur",
            name="type_membre",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
