# Generated by Django 5.2 on 2025-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0003_profilutilisateur_type_membre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilutilisateur",
            name="type_de_membre",
        ),
        migrations.RemoveField(
            model_name="profilutilisateur",
            name="type_membre",
        ),
        migrations.AddField(
            model_name="profilutilisateur",
            name="poste",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Intitulé du poste"
            ),
        ),
    ]
