# Generated by Django 5.1.7 on 2025-04-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0004_remove_profilutilisateur_type_de_membre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjetConnecte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("capteur", "Capteur"),
                            ("imprimante", "Imprimante"),
                            ("thermostat", "Thermostat"),
                            ("camera", "Caméra"),
                            ("badgeuse", "Badgeuse"),
                            ("distributeur", "Distributeur"),
                            ("table", "Table connectée"),
                            ("projecteur", "Projecteur"),
                            ("micro", "Micro"),
                            ("station", "Station de recharge"),
                            ("hub", "Hub de contrôle"),
                            ("diffuseur", "Diffuseur d’odeurs"),
                            ("led", "Mur LED"),
                            ("tapis", "Tapis connecté"),
                            ("ia", "IA prédictive"),
                            ("vocal", "Commande vocale"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("salle", models.CharField(max_length=100)),
                (
                    "niveau_requis",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        default="debutant",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
