# Generated by Django 5.1.7 on 2025-04-14 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0007_reservationsalle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="evenements_participes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservationsalle",
            name="heure",
            field=models.CharField(max_length=5),
        ),
    ]
